//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practice_2_entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.BookLoans = new HashSet<BookLoans>();
        }
    
        public int ID_Book { get; set; }
        public string Title { get; set; }
        public Nullable<int> Author_ID { get; set; }
        public Nullable<int> Genre_ID { get; set; }
        public string PublishDate { get; set; }
    
        public virtual Authors Authors { private get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookLoans> BookLoans { private get; set; }
        public virtual Genres Genres { private get; set; }
    }
}
